### ISSUE TITLE
access ports by name

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#126]
in gdsfactory you can access ports from cells and instances using 

`c.ports['o1']` or `c['o1']`

However in kfactory Kcells, this can be used to access instances (not as frequently accessed compared to ports)
How about accessing instances with `c.instances['wg1']`?

**Comment by sebastian-goeldi** [comment]
Fixed by #128

Accessing instances by name is already possible

```python
>>> import kfactory as kf
2023-05-29 17:13:59.572 | INFO     | kfactory.conf:__init__:105 - LogLevel: INFO
>>> c = kf.KCell()
>>> d = kf.KCell()
>>> inst = c << d
>>> inst.name = "inst1"
>>> c.insts["inst1"]
Unnamed_0: ports [], Unnamed_1: ports [], 0 instances
```
