### ISSUE TITLE
enable non-manhattan grid snapping issues

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#134]
```python
import kfactory as kf

c = kf.KCell()
bend = kf.cells.circular.bend_circular(
    width=1, radius=10, layer=kf.kcl.layer(1, 0), theta=30
)
b1 = c << bend
b2 = c << bend
b2.connect("o1", b1.ports["o2"])

c.draw_ports()
c.show()
```

creates less than 1nm gaps

![image](https://github.com/gdsfactory/kfactory/assets/4514346/ff69f1cd-33a6-4310-bf70-14a6106d9ac4)

How could we fix this?

@sebastian-goeldi

**Comment by joamatab** [comment]
the solution is to just flatten the instance

![image](https://github.com/gdsfactory/kfactory/assets/4514346/87b61ada-9cfd-45b6-8267-78ceb2e0d2a3)

**Comment by sebastian-goeldi** [comment]
btw there is a test for this too. But you aren´t  always guaranteed that this fixes the problem. It does in most cases, but non-theless it's not without danger, esp if you intentionally create floating points that land exactly between two grid points. One will be rounding towards and one away
