### ISSUE TITLE
Virtual Cells

### ISSUE THREAD

**Issue by sebastian-goeldi** [gdsfactory/kfactory#178]
**Is your feature request related to a problem? Please describe.**
Currently, there is no good way in kfactory for doing all-angle routing or ,more generally speaking ways, of handling off-grid  operations that will be snapped later on.

**Describe the solution you'd like**
We can use virtual cells:

* Acts like a normal KCell wrt transformation and connections, but allows arbitrary angles and positions off-grid
* Internally a fully virtual KCell (let's call it a VCell) is collection of DPolygons and ports (DCplxTrans ports) or a proxy for a virtual instance of a KCell.
* Upon insertion of a VCell, all DPolygons and proxies are flattened into the new parent cell. This should ensure all the DPolygons are flattened with enough accuracy to avoid 1nm gaps or mismatches.
* Ensure when inserted into a KCell, there are either no ports or only 90° ports that are snapped to a polygon edge

@joamatab 
@SkandanC 
@tvt173

**Comment by SkandanC** [comment]
So everytime a DPolygon is added, is gets added to a virtual kcell, which is flattebed, and addded back to the kcell?
________________________________
From: Sebastian Goeldi ***@***.***>
Sent: Wednesday, September 6, 2023 4:50 PM
To: gdsfactory/kfactory ***@***.***>
Cc: Skandan Chandrasekar ***@***.***>; Mention ***@***.***>
Subject: [gdsfactory/kfactory] Virtual DCells (Issue #178)


Is your feature request related to a problem? Please describe.
Currently, there is no good way in kfactory for doing all-angle routing or ,more generally speaking ways, of handling off-grid operations that will be snapped later on.

Describe the solution you'd like
We can use virtual cells:

  *   Acts like a normal KCell wrt transformation and connections, but allows arbitrary angles and positions off-grid
  *   Internally a fully virtual KCell (let's call it a VCell) is collection of DPolygons and ports (DCplxTrans ports) or a proxy for a virtual instance of a KCell.
  *   Upon insertion of a VCell, all DPolygons and proxies are flattened into the new parent cell. This should ensure all the DPolygons are flattened with enough accuracy to avoid 1nm gaps or mismatches.
  *   Ensure when inserted into a KCell, there are either no ports or only 90° ports that are snapped to a polygon edge

@joamatab<https://github.com/joamatab>
@SkandanC<https://github.com/SkandanC>
@tvt173<https://github.com/tvt173>

**Comment by sebastian-goeldi** [comment]
No, you first defines your VCell and then upon `KCell.create_instance / __lshift__` it will be converted / flattened and inserted into the KCell. But the VCell itself can stay as a container similar to how KCell / Instance work together

**Comment by SkandanC** [comment]
Ah ok, but does flattening  "on the go" have any advantage over flattend before write to gds?
________________________________

**Comment by sebastian-goeldi** [comment]
It's mainly about origins of Instances, they must be on grid. So as long as you are allowing traditional Instances, there will be flattening.

**Comment by sebastian-goeldi** [comment]
Closed by #228
