### ISSUE TITLE
fix `name in cell.ports`

### ISSUE THREAD

**Issue by gdspaul** [gdsfactory/kfactory#182]
**Describe the bug**
`in` predicate doesn't work for `KCell.ports`

**To Reproduce**
```
import kfactory as kf

c = kf.KCell()
c.create_port(name="Foo", width=1, trans=kf.kdb.Trans(), layer=1)

assert "Foo" in c.ports
```

**Comment by sebastian-goeldi** [comment]
hmmm, maybe we can do this. The reason it doesn't currently work is because it is not a true dictionary. It is a list that is given the dictionary-lite treatement.
