### ISSUE TITLE
offgrid ports

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#196]
When defining a width that creates off-grid points the show metadata ports is not consistent

```
c = straight(cross_section="xs_sc", width=15e-3, length=15e-3)

```

![image](https://github.com/gdsfactory/kfactory/assets/4514346/511ef5c1-71e3-45b7-b879-9f861737409c)

@sebastian-goeldi

**Comment by sebastian-goeldi** [comment]
Yeah, that's because the metdataports is a lazy implementation on my side ;). Also, I believe ports get forced on grid where possible

**Comment by sebastian-goeldi** [comment]
Should now be possible with virtual cells. It was possible even before if snapping was disabled. But we cannot support ports with off-grid widths, as that makes it complicated and very error-prone.
