### ISSUE TITLE
compatible with older versions of klayout

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#216]
How can we make kfactory compatible with older versions of klayout?

at the moment the layout shows empty

i think is because a bug on the older versions not supporting gds metadata

**Comment by sebastian-goeldi** [comment]
That's a bug on klayout's side. (and I believe it only affects the top cell not other cells)

There are 2 options:
- store without metadata (set context=False in the options)
- make a fake top cell (not sure that will work great)

**Comment by sebastian-goeldi** [comment]
@joamatab thoughts?
