### ISSUE TITLE
limit the max number of characters in the naming of kfactory,

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#227]
How can we limit the max number of characters in the naming of kfactory cells?

im getting some components with more than 200 characters

**Comment by sebastian-goeldi** [comment]
`c.write(filename, options=kf.save_layout_options(gds2_max_cellname_length=n_chars)`
From here:
- [gds2_max_cellname_length](https://klayout.de/doc/code/class_SaveLayoutOptions.html#method31)
