### ISSUE TITLE
All-Angle Bundle Router

### ISSUE THREAD

**Issue by sebastian-goeldi** [gdsfactory/kfactory#247]
For the gdsfactory migration to kfactory backend, we need an all-angle bundle router. I assume this will be similar to the single all-angle router based on a backbone provided.

Is that right @tvt173 ?

**Comment by joamatab** [comment]
yes, that's correct

**Comment by tvt173** [comment]
to be picky, it would be great if the API doesn't change from the existing all-angle bundle router in gdsfactory. there's quite a bit of functionality packed into it, such as custom connectors, bends, cross-sections, etc.

**Comment by sebastian-goeldi** [comment]
I think I will not get around to not at the very least drop some args/kwargs. There are no cross-sections, But I could offer `KCellEnclosure` which would be cross-section on steroids as it can do it for multiple center pieces. But for starters, I would like to avoid that.

**Comment by sebastian-goeldi** [comment]
Added by #305
