### ISSUE TITLE
get_route fails for waveguides close to each other

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#257]
```python

    c = gf.Component("waypoints_sample")
    w = gf.components.straight()
    top = c << w
    bot = c << w
    bot.d.move((0, -2))

    p0 = top.ports["o2"]
    p1 = bot.ports["o2"]

    r = gf.routing.route_single(
        c,
        p0,
        p1,
        cross_section="xs_rc",
    )
    c.show()


```

will fail

it you shift one versus the other it can work `bot.d.move((1,-2))` but it will create unnecessary long route

![image](https://github.com/gdsfactory/kfactory/assets/4514346/e38af0b9-cae2-4fb3-a6d8-cdea80286fe6)

in gdsfactory this can be more compact
![image](https://github.com/gdsfactory/kfactory/assets/4514346/d974954c-e569-4595-860c-4e1f5409b048)

**Comment by joamatab** [comment]
@damienbonneau

**Comment by sebastian-goeldi** [comment]
Can you check whether this fixes it?

https://github.com/gdsfactory/kfactory/pull/275

Also, I think this fixes the weirdly long routing

**Comment by joamatab** [comment]
not really

this is what i get
![image](https://github.com/gdsfactory/kfactory/assets/4514346/d327de61-d2ae-44b6-b84b-76a28b29d3f7)

this is how it should look like
![image](https://github.com/gdsfactory/kfactory/assets/4514346/5e515d18-5379-4358-8a88-8a9461a33dec)
