### ISSUE TITLE
support gdsfactory backend

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#274]
- [ ] add info and postprocess https://github.com/gdsfactory/kfactory/issues/272
- [ ] support x, xmin,y,ymin in um for instances and Components
- [ ] support get_bundles
- [ ] support all angle router

**Comment by sebastian-goeldi** [comment]
Here's the project for it where all the issues can go to https://github.com/orgs/gdsfactory/projects/6

Regarding 2: no (aleady supported with `d.xmin` etc, we can change to `dxmin`, but can't break the default of being in dbu anymore. That ship sailed a long time ago)

Everything else has an issue already
