### ISSUE TITLE
support KCell.min, KCell.min , Instance.xmin, INstance.ymin ... in um

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#283]
How could we support xmin, ymin, in um both for KCells and Instances?

**Comment by sebastian-goeldi** [comment]
How would you even do that?

**Comment by joamatab** [comment]
How about doing that gdsfactory side, by subclassing KCell and Instance?

**Comment by joamatab** [comment]
I see, okay, maybe then we need to make a big tutorial and explan that people need to use Instance.d.xmin instead

**Comment by sebastian-goeldi** [comment]
I think it's a reasonable request, but whether we do it in kfactory or gdsfactory is about the same amount of work with gdsfactory having to do even more wrapping because you want to inherit

**Comment by joamatab** [comment]
yes, im concerned about lots of people Pcells will break if we don't keep backwards compatibility

**Comment by joamatab** [comment]
Can we just inherit from UMKCell?

**Comment by sebastian-goeldi** [comment]
Yes you can if you are willing to call `.parent` anytime you call anything kfactory which requires a KCell
