### ISSUE TITLE
kf.show()

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#294]
how could we show connectivity checks lyrdb in klayout?

```python
    c = mzi_with_bend(radius=50)
    ly = c.connectivity_check()
    ly.save('/home/archie/Downloads/checks.lyrdb')
    # c = gf.routing.add_fiber_single(c)
    kf.show('/home/archie/Downloads/checks.lyrdb')
```

**Comment by sebastian-goeldi** [comment]
klive already supports this (and l2n for that matter):

https://github.com/gdsfactory/klive/blob/main/klayout/python/klive_server.py#L126

So, all that's left to do is to make `show` accept rdb/lyrdb file paths and pass them on to klive as `lyrdb`/`l2n` in the data json.

**Comment by sebastian-goeldi** [comment]
fixed by https://github.com/gdsfactory/kfactory/pull/296
