### ISSUE TITLE
default max name length to 99 characters

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#320]
how can we limit to 99 characters and add examples on how to use 32 as well?

the names are so long that we can't write the files to disk. [See](https://github.com/gdsfactory/gdsfactory/actions/runs/9168243840/job/25206705699)

@sebastian-goeldi

**Comment by sebastian-goeldi** [comment]
With [black magic](https://klayout.de/doc/code/class_SaveLayoutOptions.html#method31)

```python

save_opts = kf.default_save_options()
save_opts.gds2_max_cellname_length=99
```

Not sure that will limit it to truly 99 or whether it is 99 + `${n same name)`

I usually limited it to 97
