### ISSUE TITLE
how to avoid caching cells?

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#321]
![Image](https://github.com/gdsfactory/kfactory/assets/4514346/b81e66c4-6a0d-42ed-9589-6e584eedf105)

**Comment by sebastian-goeldi** [comment]
I am not entirely sure what you mean. Sure you can leave the cache away I guess, but to what end? it will just fail on save.

You can force rebuild a cell by doing `c.delete()`, but be aware I am not sure what happens to existing instances, I think they will just get deleted (of the old instance. `@cell` will rebuild if it detects a deleted cell.
