### ISSUE TITLE
klayout-stubs

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#4]
ERROR: Could not find a version that satisfies the requirement klayout-stubs; extra == "dev" (from kfactory[dev,docs]) (from versions: none)
ERROR: No matching distribution found for klayout-stubs; extra == "dev"

**Comment by sebastian-goeldi** [comment]
Yeah, then I forgot to remove it ;). These are the stub files for klayout (mainly the once for the dbcore ones).

**Comment by joamatab** [comment]
I see, i removed them from the dependencies :)
