### ISSUE TITLE
routing issues

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#410]
```python
import gdsfactory as gf

c = gf.Component()
w = gf.components.straight()
top = c << w
bot = c << w
bot.dmove((40, 0.001))

p0 = top.ports["o2"]
p1 = bot.ports["o1"]

r = gf.routing.route_single(c, p1, p0, cross_section="strip", taper=None)
c.show()
```

![Image](https://github.com/gdsfactory/kfactory/assets/4514346/2219278f-aad1-402d-92ae-44f1e96c1a3d)

**Comment by sebastian-goeldi** [comment]
It would help if your example has enough space to route an S ;)

you need 4x bend_radius. Your first port is at (10,0), your second one at (40,0.001), therefore you only have space for 3 x bend, but you need 4x.

If you do that, the router will behave as it should.

![image](https://github.com/gdsfactory/kfactory/assets/44963764/9dd1d601-19d7-4245-bf53-563fcc539e66)
