### ISSUE TITLE
changelog in docs are not up to date

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/kfactory#420]
the changelog in the docs is almost 6 months out of date.
https://gdsfactory.github.io/kfactory/changelog/

it does not reflect the changelog.md in the root of the repo, which is up to date

**Comment by sebastian-goeldi** [comment]
Found the issue. Definitely not a typo in the workflow's version matching :eyes: . Need to check on next release whether it is fixed. I triggered a build from main for now.
