### ISSUE TITLE
Object has been destroyed already in Cell.name when loading from gds

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/kfactory#424]
**Describe the bug**
When I try to load kcells from a GDS, I get the following error:
```console
  File "c:\blah.py", line 11, in <module>
    print(c.name)
          ^^^^^^
  File "C:\blah_blah\site-packages\kfactory\kcell.py", line 845, in name
    return self._kdb_cell.name
           ^^^^^^^^^^^^^^^^^^^
RuntimeError: Object has been destroyed already in Cell.name
```

**To Reproduce**

Try running this script with kfactory 0.18.0:
```python
import kfactory as kf
from pathlib import Path

ref_file_dir = Path(__file__).parent / 'references'
reference_layout = kf.KCLayout(name="reference_cells")
reference_layout.read(ref_file_dir / "my_layout_with_a_bunch_of_cells.gds", register_cells=True)
reference_cells = reference_layout.kcells
for c in reference_cells.values():
    print(c.name)
```

**Expected behavior**
Cell names for all the cells are listed... Am I doing something wrong here?

**Comment by sebastian-goeldi** [comment]
Are you sure this is directly related to kfactory? In gdsfactory there was a bug where `import_gds` was cached, causing it to reference destroyed cells.

But it's possible that `register_cells` is causing the problems here.

**Comment by tvt173** [comment]
definitely kfactory. i don't even have gdsfactory installed in my environment

**Comment by tvt173** [comment]
pretty sure it is kfactory. i am not importing gdsfactory at all in my script
