### ISSUE TITLE
raise error for imposible routes

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#433]
Routing works well for routes with enough space

```python
    c = gf.Component()
    w = gf.components.straight(length=0.1)
    top = c << w
    bot = c << w
    d = 40
    bot.dmove((d, d))

    p0 = top.ports["o2"]
    p1 = bot.ports["o1"]
    r = gf.routing.route_single(c, p0, p1, cross_section="strip", taper=None)
    c.show()
```

![image](https://github.com/user-attachments/assets/8b04246d-f672-4a41-99ec-a988f19964e6)

However when there is not enough space `d=5` the router routes backwards and usually collides with other elements. i think raising an error would be better

![image](https://github.com/user-attachments/assets/3f7db1d7-72ee-4f6b-97f8-9808689f9fbf)

**Comment by sebastian-goeldi** [comment]
The problem is, the router cannot know beforehand whether it will go roundtrip.

The logic is not good enough to have foresight or know the past. It can detect whether it collided with itself but not whether it failed.

Maybe I can do something but might not be successful.

**Comment by sebastian-goeldi** [comment]
We could raise an error, but I also think with the new routing algorithms, this can give legitimate routes if you give it the bboxes. I am not sure whether we should leave this or not.
