### ISSUE TITLE
access ports by alias

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#444]
Some times `ref.ports['o1']`  we have different port_names `ref.ports['in0']`

can we add something like?

ref.ports_by_alias['o1']

**Comment by 95-martin-orion** [comment]
On a related note, it would be convenient for [Ports](https://github.com/gdsfactory/kfactory/blob/cae36d88532a68afa5d59487a3ea18b96d5e0df8/src/kfactory/kcell.py#L6856) to implement `get`, similar to [dict.get](https://docs.python.org/3/library/stdtypes.html#dict.get).

**Comment by sebastian-goeldi** [comment]
@joamatab what I was thinking of is to do the following:

`ref.ports.copy(rename_function)` to give you a new `Ports` object. Now, the problem is that this will first apply the transformation of the instance. But I assume you want the naming scheme applied to the initial cell ports and not the transformed instance ports? In that case this will take a bit longer.

**Comment by sebastian-goeldi** [comment]
@95-martin-orion what would be the use case for a `get`? Sure it's not hard to implement, but I would like to know what would be the use case, as I struggle to see where that could ever be useful.

**Comment by sebastian-goeldi** [comment]
This has been implemented in the method mentioned above

**Comment by 95-martin-orion** [comment]
> @95-martin-orion what would be the use case for a `get`? Sure it's not hard to implement, but I would like to know what would be the use case, as I struggle to see where that could ever be useful.

This is primarily a consistency request: `Ports` already implements most of the functionality of `dict`, but not having `get` means that functions which operate on `dict`s will sometimes fail if applied to `Ports`. (I had an explicit example when I originally requested this, but I just got back from a month of vacation and can't recall where I left off...)
