### ISSUE TITLE
Function `apply_bbox()` does not work with `LayerInfo`

### ISSUE THREAD

**Issue by akshat-ja** [gdsfactory/kfactory#467]
**Describe the bug**

When `ref` is `LayerInfo` it returns False. We could add an `_is_LayerInfo()` function under `_is_int()` to check this and another if statement here in `enclosure.py` to accept the `LayerInfo` input.

Lines 988-991 in `./kfactory/enclosure.py`:
```
        if _is_int(ref):
            _ref = c.bbox(ref)
        elif _is_Region(ref):
            _ref = ref.bbox()
```

**Comment by akshat-ja** [comment]
@gdspaul

**Comment by sebastian-goeldi** [comment]
I think it's not necessary to use the type guards anymore. the type checkers got better by now.
