### ISSUE TITLE
When using vinstances the cell names have "-"

### ISSUE THREAD

**Issue by josepfargas** [gdsfactory/kfactory#485]
Is it possible to sanitize and replace "-" for "m" from cells names added as vinstances?
example:
`c.create_vinst(splitter())`

gives this name:
`splitter_MFalse_S28p0_X0p0002999883330545572_Y9p54709817424515e-06`
could it be
`splitter_MFalse_S28p0_X0p0002999883330545572_Y9p54709817424515em06`
instead?

Thanks

**Comment by sebastian-goeldi** [comment]
I mean, could, but why? `-` is fully compliant gds cellname.

**Comment by josepfargas** [comment]
Just to be consistent since that's the way it's done for user-Provided arguments in cells. 
Also tHis is breaking sOme internal tools, however we can also Go modify the iNtErnal tools. ThX!

**Comment by josepfargas** [comment]
Thanks!
