### ISSUE TITLE
allow usage in klayout embedded python

### ISSUE THREAD

**Issue by proppy** [gdsfactory/kfactory#53]
Would re-using `kfactory` component model when implementing klayout pcells for interactive usage (inside klayout gui) be within the scope of the project?

Context is the discussion about a recent refactoring of open source PDKs pcells in https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/issues/28

A few question toward this:
- does kfactory aim to feature parity with gdsfactory drawing primitive (`rectangle`, `boolean` ops, etc)
- would `KCell` just work on top of `pya` instead of `klayout.db/lay` https://github.com/gdsfactory/kfactory/blob/1bcdc7912e8c00613e8e2bcdc74cd24deef6bd11/src/kfactory/__init__.py#L6-L7
- would it makes sense to package an lite version of kfactory with less dependencies (no yaml, no scipy)

Let me know what you think!

**Comment by sebastian-goeldi** [comment]
I think it is within the scope that we can make this happen. I think the main issue being the imports. But I can see that with the following solution:

```python
try:
    import klayout.dbcore as kdb
    import klayout.lay as lay
except ImportError:
    logger.warning("Cannot find klayout modules dbcore and lay, trying to import klayout packages")
else:
    import pya as kdb
    import pya as lay
```
> does kfactory aim to feature parity with gdsfactory drawing primitive (rectangle, boolean ops, etc)
Kind of yes. But they are a bit more "advanced" as in they are built-in to klayout directly. (In the following assume `c` (and `c1, c2,...`) is an instance of `kf.KCell` and `layer_index` is either a `kf.LayerEnum` or `int`)
* rectangle:
   ```python
   c.shapes(layer_index).insert(kf.kdb.Box(left, bottom, right, top)```
* booleans:
   I would argue klayout booleans are just straight up better than gdsfactory booleans
   ```python
   region = kf.kdb.Region(c1.begin_shapes_rec(layer_index)) # get all shapes (recursively from cell c1)
   region2 = kf.kdb.Region()
   region2.insert(kf.kdb.Box(0, 500, 1000, -500))
   # can do this an arbitrary amount of times

   # boolean operations
   sub_region = region - region2 # r NOT r2
   add_region = region + region2 # r OR r2
   and_region = region & region2 # r AND r2
   xor_region = region ^ region2 # r XOR r2```
   
> would `KCell` just work on top of `pya` instead of `klayout.db/lay`
Yes, pya contains both and more (such as Qt objects)

> would it makes sense to package an lite version of kfactory with less dependencies (no yaml, no scipy)
We can do that. `scipy` purely a requirement for some pcells, e.g. the euler bends depend on it, so if those are stripped out, no problem at all to remove the `scipy`. As for yaml, I guess so. The thing you lose there is the placer and yaml <-> KCell, but I think for a GUI flow that would be an edge case at best anyway.

**Comment by joamatab** [comment]
we are in the process of evaluation kfactory as the backend for gdsfactory

https://github.com/gdsfactory/gdsfactory/issues/1031

Now that kfactory supports complex cells we could fully support all gdsfactory features

**Comment by sebastian-goeldi** [comment]
@proppy is this still something you'd be interested in? I think we could implement a stripped down version kfactory for this, but I think with the current dependencies, some of then deeply rooted in the code, I won't be able to support a simply try/except import of klayout/pya

**Comment by joamatab** [comment]
@mabrains
@atork
@proppy

**Comment by proppy** [comment]
@sebastian-goeldi, sorry for the late follow-up.

I think @atorkmabrains would definitly be interested to use something like this for:
https://github.com/mabrains/sky130_klayout_pdk
and 
https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pv

**Comment by proppy** [comment]
> I'd also be interested in helping make klayout more portable i.e. having it compiled against conda envs

for conda-env, we already maintain some conda packages for klayout (w/ GUI) in this channel:
https://anaconda.org/LiteX-Hub/klayout/files

It would be nice to have them part of conda-forge as well, there was some work done toward that in:
https://github.com/conda-forge/staged-recipes/pull/22419
https://github.com/conda-forge/staged-recipes/pull/20396
https://github.com/conda-forge/staged-recipes/pull/20475
https://github.com/conda-forge/staged-recipes/pull/21131

**Comment by proppy** [comment]
> at the moment evolving too fast

you mean evolving in backward incompatible way? I would have to assume that in order to be "embedded" in klayout built-in python environment, one would have to bundle all the dependencies in the klayout salt package.
