### ISSUE TITLE
python3.7 compatibility

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#8]
How can we keep python3.7 compatibility? it's still not end of live and Google colab still uses it

**Comment by SkandanC** [comment]
Perhaps as a temporary workaround, we can use [Conda Colab](https://github.com/conda-incubator/condacolab)? I use this pretty often, and haven't had any issues with it and is pretty starightforward to use.

**Comment by joamatab** [comment]
maybe it's okay to keep only >=3.8 python compatibility
